In [57]:

import pymongo
import pandas as pd
pd.set_option("display.max_columns",None)
import warnings
warnings.filterwarnings("ignore")

In [62]:

Client= pymongo.MongoClient("mongodb+srv://admin1:admin@cluster0.yziqrlb.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0")

db= Client["sample_airbnb"]
coll= db["listingsAndReviews"]

In [63]:

data= []

for i in coll.find({},{"_id":1, "listing_url":1, "name":1, 'property_type':1, 'room_type':1, 'bed_type':1, 'minimum_nights':1, 'maximum_nights':1, 'cancellation_policy':1, 'accommodates':1, 'bedrooms':1, 'beds':1, 'number_of_reviews':1, 'bathrooms':1, 'price':1, 'extra_people':1, 'guests_included':1, 'images.picture_url':1, 'review_scores':1,'cleaning_fee':1}):
    data.append(i)
data

In [65]:

df_1= pd.DataFrame(data)

In [66]:

df_1.head()

,_id,listing_url,name,property_type,room_type,bed_type,minimum_nights,maximum_nights,cancellation_policy,accommodates,bedrooms,beds,number_of_reviews,bathrooms,price,extra_people,guests_included,images,review_scores,cleaning_fee
0,10059872,https://www.airbnb.com/rooms/10059872,"Soho Cozy, Spacious and Convenient",Apartment,Entire home/apt,Real Bed,4,20,flexible,3,1.0,2.0,3,1.0,699.00,0.00,1,{'picture_url': 'https://a0.muscache.com/im/pi...,"{'review_scores_accuracy': 10, 'review_scores_...",NaN
1,10057447,https://www.airbnb.com/rooms/10057447,Modern Spacious 1 Bedroom Loft,Apartment,Entire home/apt,Real Bed,1,1125,flexible,4,1.0,2.0,0,1.0,50.00,31.00,1,{'picture_url': 'https://a0.muscache.com/im/pi...,{},NaN
2,1001265,https://www.airbnb.com/rooms/1001265,Ocean View Waikiki Marina w/prkg,Condominium,Entire home/apt,Real Bed,3,365,strict_14_with_grace_period,2,1.0,1.0,96,1.0,115.00,0.00,1,{'picture_url': 'https://a0.muscache.com/im/pi...,"{'review_scores_accuracy': 9, 'review_scores_c...",100.00
3,10030955,https://www.airbnb.com/rooms/10030955,Apt Linda Vista Lagoa - Rio,Apartment,Private room,Real Bed,1,1125,flexible,2,1.0,1.0,0,2.0,701.00,0.00,1,{'picture_url': 'https://a0.muscache.com/im/pi...,{},250.00
4,10047964,https://www.airbnb.com/rooms/10047964,Charming Flat in Downtown Moda,House,Entire home/apt,Real Bed,2,1125,flexible,6,2.0,6.0,1,1.0,527.00,211.00,1,{'picture_url': 'https://a0.muscache.com/im/pi...,"{'review_scores_accuracy': 10, 'review_scores_...",211.00

In [67]:
df_1["images"]= df_1["images"].apply(lambda x: x["picture_url"])

In [68]:
df_1["review_scores"]= df_1["review_scores"].apply(lambda x: x.get("review_scores_rating",0))

In [69]:

df_1.describe()

,accommodates,bedrooms,beds,number_of_reviews,review_scores
count,5555.000000,5550.000000,5542.000000,5555.000000,5555.000000
mean,3.505851,1.411712,2.071454,27.606481,68.395680
std,2.297019,1.041942,1.619660,49.798376,41.829834
min,1.000000,0.000000,0.000000,0.000000,0.000000
25%,2.000000,1.000000,1.000000,1.000000,0.000000
50%,3.000000,1.000000,2.000000,5.000000,92.000000
75%,4.000000,2.000000,3.000000,32.000000,98.000000
max,16.000000,20.000000,25.000000,533.000000,100.000000

In [70]:

df_1.isnull().sum()

_id                       0
listing_url               0
name                      0
property_type             0
room_type                 0
bed_type                  0
minimum_nights            0
maximum_nights            0
cancellation_policy       0
accommodates              0
bedrooms                  5
beds                     13
number_of_reviews         0
bathrooms                10
price                     0
extra_people              0
guests_included           0
images                    0
review_scores             0
cleaning_fee           1531
dtype: int64

In [71]:

#Handling the Null Vaulues
# The Null Values Feauturs are 
#beds                     
#bedrooms                  
#bathrooms                
#cleaning_fee

In [72]:
df_1["beds"].fillna(0,inplace= True)
df_1["bedrooms"].fillna(0,inplace= True)
df_1["bathrooms"].fillna(0,inplace= True)
df_1["cleaning_fee"].fillna(0,inplace= True)

In [73]:

df_1.isnull().sum()

_id                    0
listing_url            0
name                   0
property_type          0
room_type              0
bed_type               0
minimum_nights         0
maximum_nights         0
cancellation_policy    0
accommodates           0
bedrooms               0
beds                   0
number_of_reviews      0
bathrooms              0
price                  0
extra_people           0
guests_included        0
images                 0
review_scores          0
cleaning_fee           0
dtype: int64

In [74]:

# All Null Values are Cleared

In [75]:

#Handling the DataTypes

df_1.head()

,_id,listing_url,name,property_type,room_type,bed_type,minimum_nights,maximum_nights,cancellation_policy,accommodates,bedrooms,beds,number_of_reviews,bathrooms,price,extra_people,guests_included,images,review_scores,cleaning_fee
0,10059872,https://www.airbnb.com/rooms/10059872,"Soho Cozy, Spacious and Convenient",Apartment,Entire home/apt,Real Bed,4,20,flexible,3,1.0,2.0,3,1.0,699.00,0.00,1,https://a0.muscache.com/im/pictures/4533a1dc-6...,100,0
1,10057447,https://www.airbnb.com/rooms/10057447,Modern Spacious 1 Bedroom Loft,Apartment,Entire home/apt,Real Bed,1,1125,flexible,4,1.0,2.0,0,1.0,50.00,31.00,1,https://a0.muscache.com/im/pictures/9fa69ad8-c...,0,0
2,1001265,https://www.airbnb.com/rooms/1001265,Ocean View Waikiki Marina w/prkg,Condominium,Entire home/apt,Real Bed,3,365,strict_14_with_grace_period,2,1.0,1.0,96,1.0,115.00,0.00,1,https://a0.muscache.com/im/pictures/15037101/5...,84,100.00
3,10030955,https://www.airbnb.com/rooms/10030955,Apt Linda Vista Lagoa - Rio,Apartment,Private room,Real Bed,1,1125,flexible,2,1.0,1.0,0,2.0,701.00,0.00,1,https://a0.muscache.com/im/pictures/59c516bd-c...,0,250.00
4,10047964,https://www.airbnb.com/rooms/10047964,Charming Flat in Downtown Moda,House,Entire home/apt,Real Bed,2,1125,flexible,6,2.0,6.0,1,1.0,527.00,211.00,1,https://a0.muscache.com/im/pictures/231120b6-e...,100,211.00

In [76]:

df_1.dtypes

_id                     object
listing_url             object
name                    object
property_type           object
room_type               object
bed_type                object
minimum_nights          object
maximum_nights          object
cancellation_policy     object
accommodates             int64
bedrooms               float64
beds                   float64
number_of_reviews        int64
bathrooms               object
price                   object
extra_people            object
guests_included         object
images                  object
review_scores            int64
cleaning_fee            object
dtype: object

In [77]:

df_1["minimum_nights"]= df_1["minimum_nights"].astype(int)
df_1["maximum_nights"]= df_1["maximum_nights"].astype(int)
df_1["bedrooms"]= df_1["bedrooms"].astype(int)
df_1["beds"]= df_1["beds"].astype(int)
df_1["bathrooms"]= df_1["bathrooms"].astype(str).astype(float).astype(int)
df_1["price"]= df_1["price"].astype(str).astype(float).astype(int)
df_1["extra_people"]= df_1["extra_people"].astype(str).astype(float).astype(int)
df_1["guests_included"]= df_1["guests_included"].astype(str).astype(float).astype(int)
df_1["cleaning_fee"]= df_1["cleaning_fee"].astype(str).astype(float).astype(int)

In [78]:
df_1.dtypes

_id                    object
listing_url            object
name                   object
property_type          object
room_type              object
bed_type               object
minimum_nights          int32
maximum_nights          int32
cancellation_policy    object
accommodates            int64
bedrooms                int32
beds                    int32
number_of_reviews       int64
bathrooms               int32
price                   int32
extra_people            int32
guests_included         int32
images                 object
review_scores           int64
cleaning_fee            int32
dtype: object

In [79]:

#Collect the Host Details

host= []
for i in coll.find({},{"_id":1, "host":1}):
    host.append(i)
host

In [81]:

df_host= pd.DataFrame(host)
df_host

           _id                                               host
0     10059872  {'host_id': '51624384', 'host_url': 'https://w...
1     10057447  {'host_id': '51612949', 'host_url': 'https://w...
2      1001265  {'host_id': '5448114', 'host_url': 'https://ww...
3     10030955  {'host_id': '51496939', 'host_url': 'https://w...
4     10047964  {'host_id': '1241644', 'host_url': 'https://ww...
...        ...                                                ...
5550   9983221  {'host_id': '37776205', 'host_url': 'https://w...
5551   9987200  {'host_id': '51314789', 'host_url': 'https://w...
5552   9985696  {'host_id': '51303748', 'host_url': 'https://w...
5553   9990304  {'host_id': '51013381', 'host_url': 'https://w...
5554   9993190  {'host_id': '51013381', 'host_url': 'https://w...

[5555 rows x 2 columns]

In [82]:
host_columns= {'_id':[],'host_id':[], 'host_url':[], 'host_name':[], 'host_location':[],"host_response_time":[], 'host_thumbnail_url':[], 'host_picture_url':[], 'host_neighbourhood':[], 'host_response_rate':[], 'host_is_superhost':[], 'host_has_profile_pic':[], 'host_identity_verified':[], 'host_listings_count':[], 'host_total_listings_count':[], 'host_verifications':[]}

for i in df_host["_id"]:
    host_columns["_id"].append(i)
for i in df_host["host"]:
    host_columns["host_id"].append(i["host_id"])
    host_columns["host_url"].append(i["host_url"])
    host_columns["host_name"].append(i["host_name"])
    host_columns["host_location"].append(i["host_location"])
    host_columns["host_response_time"].append(i.get("host_response_time"))
    host_columns["host_thumbnail_url"].append(i["host_thumbnail_url"])
    host_columns["host_picture_url"].append(i["host_picture_url"])
    host_columns["host_neighbourhood"].append(i["host_neighbourhood"])
    host_columns["host_response_rate"].append(i.get("host_response_rate"))
    host_columns["host_is_superhost"].append(i["host_is_superhost"])
    host_columns["host_has_profile_pic"].append(i["host_has_profile_pic"])
    host_columns["host_identity_verified"].append(i["host_identity_verified"])
    host_columns["host_listings_count"].append(i["host_listings_count"])
    host_columns["host_total_listings_count"].append(i["host_total_listings_count"])
    host_columns["host_verifications"].append(i["host_verifications"])

In [83]:

df_host_1= pd.DataFrame(host_columns)

In [84]:
df_host_1

,_id,host_id,host_url,host_name,host_location,host_response_time,host_thumbnail_url,host_picture_url,host_neighbourhood,host_response_rate,host_is_superhost,host_has_profile_pic,host_identity_verified,host_listings_count,host_total_listings_count,host_verifications
0,10059872,51624384,https://www.airbnb.com/users/show/51624384,Giovanni,"Hong Kong, Hong Kong",None,https://a0.muscache.com/im/pictures/264b82a7-7...,https://a0.muscache.com/im/pictures/264b82a7-7...,Soho,NaN,False,True,False,1,1,"[email, phone, reviews, jumio, government_id]"
1,10057447,51612949,https://www.airbnb.com/users/show/51612949,Konstantin,"Montreal, Quebec, Canada",None,https://a0.muscache.com/im/pictures/beb6b50e-0...,https://a0.muscache.com/im/pictures/beb6b50e-0...,Mile End,NaN,False,True,False,1,1,"[email, phone, jumio, offline_government_id, s..."
2,1001265,5448114,https://www.airbnb.com/users/show/5448114,David,"Honolulu, Hawaii, United States",within an hour,https://a0.muscache.com/im/users/5448114/profi...,https://a0.muscache.com/im/users/5448114/profi...,Waikiki,98.0,False,True,False,18,18,"[email, phone, reviews, kba]"
3,10030955,51496939,https://www.airbnb.com/users/show/51496939,Livia,BR,None,https://a0.muscache.com/im/pictures/b7911710-9...,https://a0.muscache.com/im/pictures/b7911710-9...,Lagoa,NaN,False,True,False,1,1,"[email, phone, jumio, government_id]"
4,10047964,1241644,https://www.airbnb.com/users/show/1241644,Zeynep,"Istanbul, Istanbul, Turkey",None,https://a0.muscache.com/im/users/1241644/profi...,https://a0.muscache.com/im/users/1241644/profi...,Moda,NaN,False,True,True,2,2,"[email, phone, facebook, reviews, jumio, gover..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5550,9983221,37776205,https://www.airbnb.com/users/show/37776205,Ana,Portugal,within an hour,https://a0.muscache.com/im/users/37776205/prof...,https://a0.muscache.com/im/users/37776205/prof...,,100.0,True,True,False,8,8,"[email, phone, reviews, offline_government_id,..."
5551,9987200,51314789,https://www.airbnb.com/users/show/51314789,Dumont,"Rio de Janeiro, State of Rio de Janeiro, Brazil",within an hour,https://a0.muscache.com/im/pictures/65582ca0-8...,https://a0.muscache.com/im/pictures/65582ca0-8...,Copacabana,100.0,True,True,True,3,3,"[email, phone, reviews, jumio, government_id, ..."
5552,9985696,51303748,https://www.airbnb.com/users/show/51303748,Eren,"Kadikoy, Çanakkale, Turkey",None,https://a0.muscache.com/im/pictures/89a1b839-2...,https://a0.muscache.com/im/pictures/89a1b839-2...,,NaN,False,True,False,2,2,"[email, phone]"
5553,9990304,51013381,https://www.airbnb.com/users/show/51013381,Coconut Condos,"Lahaina, Hawaii, United States",within an hour,https://a0.muscache.com/im/pictures/fa071e13-8...,https://a0.muscache.com/im/pictures/fa071e13-8...,,99.0,False,True,True,58,58,"[email, phone, reviews, kba, work_email]"
5554,9993190,51013381,https://www.airbnb.com/users/show/51013381,Coconut Condos,"Lahaina, Hawaii, United States",within an hour,https://a0.muscache.com/im/pictures/fa071e13-8...,https://a0.muscache.com/im/pictures/fa071e13-8...,,99.0,False,True,True,58,58,"[email, phone, reviews, kba, work_email]"

In [85]:

df_host_1.head()

,_id,host_id,host_url,host_name,host_location,host_response_time,host_thumbnail_url,host_picture_url,host_neighbourhood,host_response_rate,host_is_superhost,host_has_profile_pic,host_identity_verified,host_listings_count,host_total_listings_count,host_verifications
0,10059872,51624384,https://www.airbnb.com/users/show/51624384,Giovanni,"Hong Kong, Hong Kong",None,https://a0.muscache.com/im/pictures/264b82a7-7...,https://a0.muscache.com/im/pictures/264b82a7-7...,Soho,NaN,False,True,False,1,1,"[email, phone, reviews, jumio, government_id]"
1,10057447,51612949,https://www.airbnb.com/users/show/51612949,Konstantin,"Montreal, Quebec, Canada",None,https://a0.muscache.com/im/pictures/beb6b50e-0...,https://a0.muscache.com/im/pictures/beb6b50e-0...,Mile End,NaN,False,True,False,1,1,"[email, phone, jumio, offline_government_id, s..."
2,1001265,5448114,https://www.airbnb.com/users/show/5448114,David,"Honolulu, Hawaii, United States",within an hour,https://a0.muscache.com/im/users/5448114/profi...,https://a0.muscache.com/im/users/5448114/profi...,Waikiki,98.0,False,True,False,18,18,"[email, phone, reviews, kba]"
3,10030955,51496939,https://www.airbnb.com/users/show/51496939,Livia,BR,None,https://a0.muscache.com/im/pictures/b7911710-9...,https://a0.muscache.com/im/pictures/b7911710-9...,Lagoa,NaN,False,True,False,1,1,"[email, phone, jumio, government_id]"
4,10047964,1241644,https://www.airbnb.com/users/show/1241644,Zeynep,"Istanbul, Istanbul, Turkey",None,https://a0.muscache.com/im/users/1241644/profi...,https://a0.muscache.com/im/users/1241644/profi...,Moda,NaN,False,True,True,2,2,"[email, phone, facebook, reviews, jumio, gover..."

In [86]:

df_host_1.isnull().sum()

_id                             0
host_id                         0
host_url                        0
host_name                       0
host_location                   0
host_response_time           1388
host_thumbnail_url              0
host_picture_url                0
host_neighbourhood              0
host_response_rate           1388
host_is_superhost               0
host_has_profile_pic            0
host_identity_verified          0
host_listings_count             0
host_total_listings_count       0
host_verifications              0
dtype: int64

In [87]:
#Checking the "host_neighbourhood" details
# host_neighbourhood have more empty values ('')
# Finding the how many values are empty
list_index= []
for index,row in df_host_1.iterrows():
    if row["host_neighbourhood"] =='':
        list_index.append(index)

In [88]:

len(list_index)

1923

In [89]:
df_host_1["host_response_time"].fillna("Not Specified",inplace= True)
df_host_1["host_response_rate"].fillna("Not Specified",inplace= True)
df_host_1["host_neighbourhood"]= df_host_1["host_neighbourhood"].replace({'':"Not Specified"})

In [90]:

df_host_1

,_id,host_id,host_url,host_name,host_location,host_response_time,host_thumbnail_url,host_picture_url,host_neighbourhood,host_response_rate,host_is_superhost,host_has_profile_pic,host_identity_verified,host_listings_count,host_total_listings_count,host_verifications
0,10059872,51624384,https://www.airbnb.com/users/show/51624384,Giovanni,"Hong Kong, Hong Kong",Not Specified,https://a0.muscache.com/im/pictures/264b82a7-7...,https://a0.muscache.com/im/pictures/264b82a7-7...,Soho,Not Specified,False,True,False,1,1,"[email, phone, reviews, jumio, government_id]"
1,10057447,51612949,https://www.airbnb.com/users/show/51612949,Konstantin,"Montreal, Quebec, Canada",Not Specified,https://a0.muscache.com/im/pictures/beb6b50e-0...,https://a0.muscache.com/im/pictures/beb6b50e-0...,Mile End,Not Specified,False,True,False,1,1,"[email, phone, jumio, offline_government_id, s..."
2,1001265,5448114,https://www.airbnb.com/users/show/5448114,David,"Honolulu, Hawaii, United States",within an hour,https://a0.muscache.com/im/users/5448114/profi...,https://a0.muscache.com/im/users/5448114/profi...,Waikiki,98.0,False,True,False,18,18,"[email, phone, reviews, kba]"
3,10030955,51496939,https://www.airbnb.com/users/show/51496939,Livia,BR,Not Specified,https://a0.muscache.com/im/pictures/b7911710-9...,https://a0.muscache.com/im/pictures/b7911710-9...,Lagoa,Not Specified,False,True,False,1,1,"[email, phone, jumio, government_id]"
4,10047964,1241644,https://www.airbnb.com/users/show/1241644,Zeynep,"Istanbul, Istanbul, Turkey",Not Specified,https://a0.muscache.com/im/users/1241644/profi...,https://a0.muscache.com/im/users/1241644/profi...,Moda,Not Specified,False,True,True,2,2,"[email, phone, facebook, reviews, jumio, gover..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5550,9983221,37776205,https://www.airbnb.com/users/show/37776205,Ana,Portugal,within an hour,https://a0.muscache.com/im/users/37776205/prof...,https://a0.muscache.com/im/users/37776205/prof...,Not Specified,100.0,True,True,False,8,8,"[email, phone, reviews, offline_government_id,..."
5551,9987200,51314789,https://www.airbnb.com/users/show/51314789,Dumont,"Rio de Janeiro, State of Rio de Janeiro, Brazil",within an hour,https://a0.muscache.com/im/pictures/65582ca0-8...,https://a0.muscache.com/im/pictures/65582ca0-8...,Copacabana,100.0,True,True,True,3,3,"[email, phone, reviews, jumio, government_id, ..."
5552,9985696,51303748,https://www.airbnb.com/users/show/51303748,Eren,"Kadikoy, Çanakkale, Turkey",Not Specified,https://a0.muscache.com/im/pictures/89a1b839-2...,https://a0.muscache.com/im/pictures/89a1b839-2...,Not Specified,Not Specified,False,True,False,2,2,"[email, phone]"
5553,9990304,51013381,https://www.airbnb.com/users/show/51013381,Coconut Condos,"Lahaina, Hawaii, United States",within an hour,https://a0.muscache.com/im/pictures/fa071e13-8...,https://a0.muscache.com/im/pictures/fa071e13-8...,Not Specified,99.0,False,True,True,58,58,"[email, phone, reviews, kba, work_email]"
5554,9993190,51013381,https://www.airbnb.com/users/show/51013381,Coconut Condos,"Lahaina, Hawaii, United States",within an hour,https://a0.muscache.com/im/pictures/fa071e13-8...,https://a0.muscache.com/im/pictures/fa071e13-8...,Not Specified,99.0,False,True,True,58,58,"[email, phone, reviews, kba, work_email]"

In [91]:
# Changing the "True" or "False" features

df_host_1["host_is_superhost"]= df_host_1["host_is_superhost"].map({False: "No", True: "Yes"})
df_host_1["host_has_profile_pic"]= df_host_1["host_has_profile_pic"].map({False: "No", True: "Yes"})
df_host_1["host_identity_verified"]= df_host_1["host_identity_verified"].map({False: "No", True: "Yes"})

In [92]:
df_host_1.head()

,_id,host_id,host_url,host_name,host_location,host_response_time,host_thumbnail_url,host_picture_url,host_neighbourhood,host_response_rate,host_is_superhost,host_has_profile_pic,host_identity_verified,host_listings_count,host_total_listings_count,host_verifications
0,10059872,51624384,https://www.airbnb.com/users/show/51624384,Giovanni,"Hong Kong, Hong Kong",Not Specified,https://a0.muscache.com/im/pictures/264b82a7-7...,https://a0.muscache.com/im/pictures/264b82a7-7...,Soho,Not Specified,No,Yes,No,1,1,"[email, phone, reviews, jumio, government_id]"
1,10057447,51612949,https://www.airbnb.com/users/show/51612949,Konstantin,"Montreal, Quebec, Canada",Not Specified,https://a0.muscache.com/im/pictures/beb6b50e-0...,https://a0.muscache.com/im/pictures/beb6b50e-0...,Mile End,Not Specified,No,Yes,No,1,1,"[email, phone, jumio, offline_government_id, s..."
2,1001265,5448114,https://www.airbnb.com/users/show/5448114,David,"Honolulu, Hawaii, United States",within an hour,https://a0.muscache.com/im/users/5448114/profi...,https://a0.muscache.com/im/users/5448114/profi...,Waikiki,98.0,No,Yes,No,18,18,"[email, phone, reviews, kba]"
3,10030955,51496939,https://www.airbnb.com/users/show/51496939,Livia,BR,Not Specified,https://a0.muscache.com/im/pictures/b7911710-9...,https://a0.muscache.com/im/pictures/b7911710-9...,Lagoa,Not Specified,No,Yes,No,1,1,"[email, phone, jumio, government_id]"
4,10047964,1241644,https://www.airbnb.com/users/show/1241644,Zeynep,"Istanbul, Istanbul, Turkey",Not Specified,https://a0.muscache.com/im/users/1241644/profi...,https://a0.muscache.com/im/users/1241644/profi...,Moda,Not Specified,No,Yes,Yes,2,2,"[email, phone, facebook, reviews, jumio, gover..."

In [93]:
#Collect the Address Details

address= []
for i in coll.find({}, {"_id":1, "address":1}):
    address.append(i)

In [94]:

df_address= pd.DataFrame(address)

In [95]:
address_columns= {'_id':[], 'street':[], 'suburb':[], 'government_area':[], 'market':[], 'country':[],
                   'country_code':[], 'location_type':[], "longitude":[], "latitude":[],
                    "is_location_exact":[]}

for i in df_address["_id"]:
    address_columns["_id"].append(i)

for i in df_address["address"]:
    address_columns["street"].append(i["street"])
    address_columns["suburb"].append(i["suburb"])
    address_columns["government_area"].append(i["government_area"])
    address_columns["market"].append(i["market"])
    address_columns["country"].append(i["country"])
    address_columns["country_code"].append(i["country_code"])
    address_columns["location_type"].append(i["location"]["type"])
    address_columns["longitude"].append(i["location"]["coordinates"][0])
    address_columns["latitude"].append(i["location"]["coordinates"][1])
    address_columns["is_location_exact"].append(i["location"]["is_location_exact"])
df_address_1= pd.DataFrame(address_columns)

In [96]:

df_address_1= pd.DataFrame(address_columns)

In [97]:

df_address_1.head()

,_id,street,suburb,government_area,market,country,country_code,location_type,longitude,latitude,is_location_exact
0,10059872,"Hong Kong, Hong Kong Island, Hong Kong",Central & Western District,Central & Western,Hong Kong,Hong Kong,HK,Point,114.150270,22.281580,True
1,10057447,"Montréal, Québec, Canada",Mile End,Le Plateau-Mont-Royal,Montreal,Canada,CA,Point,-73.591110,45.518890,True
2,1001265,"Honolulu, HI, United States",Oʻahu,Primary Urban Center,Oahu,United States,US,Point,-157.839190,21.286340,True
3,10030955,"Rio de Janeiro, Rio de Janeiro, Brazil",Lagoa,Lagoa,Rio De Janeiro,Brazil,BR,Point,-43.205047,-22.971951,True
4,10047964,"Kadıköy, İstanbul, Turkey",Moda,Kadikoy,Istanbul,Turkey,TR,Point,29.031330,40.985850,True

In [98]:

df_address_1.isnull().sum()

_id                  0
street               0
suburb               0
government_area      0
market               0
country              0
country_code         0
location_type        0
longitude            0
latitude             0
is_location_exact    0
dtype: int64

In [99]:
# Checking the empty values ('') for all features

#for i in df_address_1.columns:
id_e=[]
stre_e=[]
suburb_e=[]
gov_e=[]
mark_e=[]
cntry_e=[]
cntry_co_e=[]
loc_ty_e=[]
long_e=[]
lat_e=[]
is_loc_tr_e=[]
for index,row in df_address_1.iterrows():
    if row["_id"] == '':
        id_e.append(index)

    if row["street"] == '':
        stre_e.append(index)
        
    if row["suburb"] == '':
        suburb_e.append(index)

    if row["government_area"] == '':
        gov_e.append(index)

    if row["market"] == '':
        mark_e.append(index)

    if row["country"] == '':
        cntry_e.append(index)
    
    if row["country_code"] == '':
        cntry_co_e.append(index)

    if row["location_type"] == '':
        loc_ty_e.append(index) 

    if row["longitude"] == '':
        long_e.append(index)

    if row["latitude"] == '':
        lat_e.append(index)

    if row["is_location_exact"] == '':
        is_loc_tr_e.append(index)

In [100]:
empty_columns=[id_e,stre_e,suburb_e,gov_e,mark_e,cntry_e,cntry_co_e,loc_ty_e,long_e,lat_e,is_loc_tr_e]
for i in empty_columns:
    print(len(i))

0
0
887
0
6
0
0
0
0
0
0

In [101]:
#Handling the empty values and Boolian Values
# "suburb" and "market" have a empty values

df_address_1["suburb"]= df_address_1["suburb"].replace({'':"Not Specified"})
df_address_1["market"]= df_address_1["market"].replace({'':"Not Specified"})

df_address_1["is_location_exact"]= df_address_1["is_location_exact"].map({False:"No", True:"Yes"})

In [102]:

df_address_1

,_id,street,suburb,government_area,market,country,country_code,location_type,longitude,latitude,is_location_exact
0,10059872,"Hong Kong, Hong Kong Island, Hong Kong",Central & Western District,Central & Western,Hong Kong,Hong Kong,HK,Point,114.150270,22.281580,Yes
1,10057447,"Montréal, Québec, Canada",Mile End,Le Plateau-Mont-Royal,Montreal,Canada,CA,Point,-73.591110,45.518890,Yes
2,1001265,"Honolulu, HI, United States",Oʻahu,Primary Urban Center,Oahu,United States,US,Point,-157.839190,21.286340,Yes
3,10030955,"Rio de Janeiro, Rio de Janeiro, Brazil",Lagoa,Lagoa,Rio De Janeiro,Brazil,BR,Point,-43.205047,-22.971951,Yes
4,10047964,"Kadıköy, İstanbul, Turkey",Moda,Kadikoy,Istanbul,Turkey,TR,Point,29.031330,40.985850,Yes
...,...,...,...,...,...,...,...,...,...,...,...
5550,9983221,"Porto, Porto, Portugal",Not Specified,"Cedofeita, Ildefonso, Sé, Miragaia, Nicolau, V...",Porto,Portugal,PT,Point,-8.616930,41.151370,No
5551,9987200,"Rio de Janeiro, Rio de Janeiro, Brazil",Copacabana,Copacabana,Rio De Janeiro,Brazil,BR,Point,-43.176533,-22.961076,Yes
5552,9985696,"Kadıköy, İstanbul, Turkey",Moda,Kadikoy,Istanbul,Turkey,TR,Point,29.030790,40.985630,No
5553,9990304,"Lahaina, HI, United States",Maui,Lahaina,Maui,United States,US,Point,-156.676460,20.875610,No
5554,9993190,"Lahaina, HI, United States",Lahaina,Lahaina,Maui,United States,US,Point,-156.667520,20.858940,No

In [103]:

#Availability
availability= []
for i in coll.find({}, {"_id":1, "availability":1}):
    availability.append(i)

In [104]:

df_availabe= pd.DataFrame(availability)

In [105]:

availabe_columns= {'_id':[], 'availability_30':[], 'availability_60':[], 'availability_90':[], 'availability_365':[]}

for i in df_availabe["_id"]:
    availabe_columns["_id"].append(i)

for i in df_availabe["availability"]:
    availabe_columns["availability_30"].append(i["availability_30"])
    availabe_columns["availability_60"].append(i["availability_60"])
    availabe_columns["availability_90"].append(i["availability_90"])
    availabe_columns["availability_365"].append(i["availability_365"])

In [106]:
df_availabe_1= pd.DataFrame(availabe_columns)

In [107]:

df_availabe_1

,_id,availability_30,availability_60,availability_90,availability_365
0,10059872,0,0,0,0
1,10057447,0,0,0,0
2,1001265,16,46,76,343
3,10030955,28,58,88,363
4,10047964,27,57,87,362
...,...,...,...,...,...
5550,9983221,26,51,77,300
5551,9987200,7,29,53,53
5552,9985696,30,60,90,365
5553,9990304,8,20,26,243
5554,9993190,0,8,31,258

In [108]:
df_availabe_1.isnull().sum()

_id                 0
availability_30     0
availability_60     0
availability_90     0
availability_365    0
dtype: int64

In [109]:
df_availabe_1.dtypes

_id                 object
availability_30      int64
availability_60      int64
availability_90      int64
availability_365     int64
dtype: object

In [110]:

amenities= []
for i in coll.find({},{"_id":1, "amenities":1}):
    amenities.append(i)

In [111]:

df_amenities= pd.DataFrame(amenities)

In [112]:
df_amenities

           _id                                          amenities
0     10059872  [Air conditioning, Kitchen, Smoking allowed, D...
1     10057447  [Internet, Wifi, Kitchen, Heating, Family/kid ...
2      1001265  [TV, Cable TV, Wifi, Air conditioning, Pool, K...
3     10030955  [TV, Cable TV, Internet, Wifi, Air conditionin...
4     10047964  [TV, Cable TV, Internet, Wifi, Kitchen, Free p...
...        ...                                                ...
5550   9983221  [TV, Cable TV, Internet, Wifi, Kitchen, Paid p...
5551   9987200  [TV, Cable TV, Wifi, Air conditioning, Pool, G...
5552   9985696  [TV, Cable TV, Internet, Wifi, Kitchen, Buzzer...
5553   9990304  [TV, Cable TV, Wifi, Air conditioning, Wheelch...
5554   9993190  [TV, Wifi, Air conditioning, Pool, Kitchen, Fr...

[5555 rows x 2 columns]

In [113]:

def sort_amenities(x):
    a= x
    a.sort()
    return a

In [114]:
df_amenities["amenities"]= df_amenities["amenities"].apply(lambda x: sort_amenities(x))

In [115]:
df_amenities

           _id                                          amenities
0     10059872  [24-hour check-in, Air conditioning, Doorman, ...
1     10057447  [24-hour check-in, Dryer, Essentials, Family/k...
2      1001265  [Air conditioning, BBQ grill, Bed linens, Cabl...
3     10030955  [24-hour check-in, Air conditioning, Buzzer/wi...
4     10047964  [24-hour check-in, Cable TV, Cat(s), Essential...
...        ...                                                ...
5550   9983221  [Bed linens, Cable TV, Cleaning before checkou...
5551   9987200  [Air conditioning, Bed linens, Building staff,...
5552   9985696  [Buzzer/wireless intercom, Cable TV, Dryer, Es...
5553   9990304  [Air conditioning, Cable TV, Dryer, Essentials...
5554   9993190  [Air conditioning, Dryer, Essentials, Family/k...

[5555 rows x 2 columns]

In [116]:

df_amenities.isnull().sum()

_id          0
amenities    0
dtype: int64

In [117]:

df_amenities.dtypes

_id          object
amenities    object
dtype: object

In [118]:

#df_1
#df_host_1
#df_address_1
#df_availabe_1
#df_amenities
df= pd.merge(df_1, df_host_1, on="_id")
df= pd.merge(df, df_address_1, on="_id")
df= pd.merge(df, df_availabe_1, on="_id")
df= pd.merge(df, df_amenities, on="_id")

In [119]:
# save the file 
df.to_csv("Airbnb.csv", index= False)

In [120]:

df= pd.read_csv("Airbnb.csv")

In [121]:
df

,_id,listing_url,name,property_type,room_type,bed_type,minimum_nights,maximum_nights,cancellation_policy,accommodates,bedrooms,beds,number_of_reviews,bathrooms,price,extra_people,guests_included,images,review_scores,cleaning_fee,host_id,host_url,host_name,host_location,host_response_time,host_thumbnail_url,host_picture_url,host_neighbourhood,host_response_rate,host_is_superhost,host_has_profile_pic,host_identity_verified,host_listings_count,host_total_listings_count,host_verifications,street,suburb,government_area,market,country,country_code,location_type,longitude,latitude,is_location_exact,availability_30,availability_60,availability_90,availability_365,amenities
0,10059872,https://www.airbnb.com/rooms/10059872,"Soho Cozy, Spacious and Convenient",Apartment,Entire home/apt,Real Bed,4,20,flexible,3,1,2,3,1,699,0,1,https://a0.muscache.com/im/pictures/4533a1dc-6...,100,0,51624384,https://www.airbnb.com/users/show/51624384,Giovanni,"Hong Kong, Hong Kong",Not Specified,https://a0.muscache.com/im/pictures/264b82a7-7...,https://a0.muscache.com/im/pictures/264b82a7-7...,Soho,Not Specified,No,Yes,No,1,1,"['email', 'phone', 'reviews', 'jumio', 'govern...","Hong Kong, Hong Kong Island, Hong Kong",Central & Western District,Central & Western,Hong Kong,Hong Kong,HK,Point,114.150270,22.281580,Yes,0,0,0,0,"['24-hour check-in', 'Air conditioning', 'Door..."
1,10057447,https://www.airbnb.com/rooms/10057447,Modern Spacious 1 Bedroom Loft,Apartment,Entire home/apt,Real Bed,1,1125,flexible,4,1,2,0,1,50,31,1,https://a0.muscache.com/im/pictures/9fa69ad8-c...,0,0,51612949,https://www.airbnb.com/users/show/51612949,Konstantin,"Montreal, Quebec, Canada",Not Specified,https://a0.muscache.com/im/pictures/beb6b50e-0...,https://a0.muscache.com/im/pictures/beb6b50e-0...,Mile End,Not Specified,No,Yes,No,1,1,"['email', 'phone', 'jumio', 'offline_governmen...","Montréal, Québec, Canada",Mile End,Le Plateau-Mont-Royal,Montreal,Canada,CA,Point,-73.591110,45.518890,Yes,0,0,0,0,"['24-hour check-in', 'Dryer', 'Essentials', 'F..."
2,1001265,https://www.airbnb.com/rooms/1001265,Ocean View Waikiki Marina w/prkg,Condominium,Entire home/apt,Real Bed,3,365,strict_14_with_grace_period,2,1,1,96,1,115,0,1,https://a0.muscache.com/im/pictures/15037101/5...,84,100,5448114,https://www.airbnb.com/users/show/5448114,David,"Honolulu, Hawaii, United States",within an hour,https://a0.muscache.com/im/users/5448114/profi...,https://a0.muscache.com/im/users/5448114/profi...,Waikiki,98.0,No,Yes,No,18,18,"['email', 'phone', 'reviews', 'kba']","Honolulu, HI, United States",Oʻahu,Primary Urban Center,Oahu,United States,US,Point,-157.839190,21.286340,Yes,16,46,76,343,"['Air conditioning', 'BBQ grill', 'Bed linens'..."
3,10030955,https://www.airbnb.com/rooms/10030955,Apt Linda Vista Lagoa - Rio,Apartment,Private room,Real Bed,1,1125,flexible,2,1,1,0,2,701,0,1,https://a0.muscache.com/im/pictures/59c516bd-c...,0,250,51496939,https://www.airbnb.com/users/show/51496939,Livia,BR,Not Specified,https://a0.muscache.com/im/pictures/b7911710-9...,https://a0.muscache.com/im/pictures/b7911710-9...,Lagoa,Not Specified,No,Yes,No,1,1,"['email', 'phone', 'jumio', 'government_id']","Rio de Janeiro, Rio de Janeiro, Brazil",Lagoa,Lagoa,Rio De Janeiro,Brazil,BR,Point,-43.205047,-22.971951,Yes,28,58,88,363,"['24-hour check-in', 'Air conditioning', 'Buzz..."
4,10047964,https://www.airbnb.com/rooms/10047964,Charming Flat in Downtown Moda,House,Entire home/apt,Real Bed,2,1125,flexible,6,2,6,1,1,527,211,1,https://a0.muscache.com/im/pictures/231120b6-e...,100,211,1241644,https://www.airbnb.com/users/show/1241644,Zeynep,"Istanbul, Istanbul, Turkey",Not Specified,https://a0.muscache.com/im/users/1241644/profi...,https://a0.muscache.com/im/users/1241644/profi...,Moda,Not Specified,No,Yes,Yes,2,2,"['email', 'phone', 'facebook', 'reviews', 'jum...","Kadıköy, İstanbul, Turkey",Moda,Kadikoy,Istanbul,Turkey,TR,Point,29.031330,40.985850,Yes,27,57,87,362,"['24-hour check-in', 'Cable TV', 'Cat(s)', 'Es..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5550,9983221,https://www.airbnb.com/rooms/9983221,Cozy apartment downtown Porto,Apartment,Entire home/apt,Real Bed,3,1125,strict_14_with_grace_period,4,1,2,107,1,58,15,2,https://a0.muscache.com/im/pictures/15b74c6a-8...,98,20,37776205,https://www.airbnb.com/users/show/37776205,Ana,Portugal,within an hour,https://a0.muscache.com/im/users/37776205/prof...,https://a0.muscache.com/im/users/37776205/prof...,Not Specified,100.0,Yes,Yes,No,8,8,"['email', 'phone', 'reviews', 'offline_governm...","Porto, Porto, Portugal",Not Specified,"Cedofeita, Ildefonso, Sé, Miragaia, Nicolau, V...",Porto,Portugal,PT,Point,-8.616930,41.151370,No,26,51,77,300,"['Bed linens', 'Cable TV', 'Cleaning before ch..."
5551,9987200,https://www.airbnb.com/rooms/9987200,The best suite in Copacabana (total privacy),Aparthotel,Private room,Real Bed,3,60,flexible,3,1,3,90,1,101,50,2,https://a0.muscache.com/im/pictures/4a2a03e4-d...,97,100,51314789,https://www.airbnb.com/users/show/51314789,Dumont,"Rio de Janeiro, State of Rio de Janeiro, Brazil",within an hour,https://a0.muscache.com/im/pictures/65582ca0-8...,https://a0.muscache.com/im/pictures/65582ca0-8...,Copacabana,100.0,Yes,Yes,Yes,3,3,"['email', 'phone', 'reviews', 'jumio', 'govern...","Rio de Janeiro, Rio de Janeiro, Brazil",Copacabana,Copacabana,Rio De Janeiro,Brazil,BR,Point,-43.176533,-22.961076,Yes,7,29,53,53,"['Air conditioning', 'Bed linens', 'Building s..."
5552,9985696,https://www.airbnb.com/rooms/9985696,Kadıköy-Altıyol,House,Entire home/apt,Real Bed,1,1125,flexible,2,2,3,0,1,501,0,1,https://a0.muscache.com/im/pictures/e40d18b2-1...,0,0,51303748,https://www.airbnb.com/users/show/51303748,Eren,"Kadikoy, Çanakkale, Turkey",Not Specified,https://a0.muscache.com/im/pictures/89a1b839-2...,https://a0.muscache.com/im/pictures/89a1b839-2...,Not Specified,Not Specified,No,Yes,No,2,2,"['email', 'phone']","Kadıköy, İstanbul, Turkey",Moda,Kadikoy,Istanbul,Turkey,TR,Point,29.030790,40.985630,No,30,60,90,365,"['Buzzer/wireless intercom', 'Cable TV', 'Drye..."
5553,9990304,https://www.airbnb.com/rooms/9990304,March Madness Special! Aina Nalu Platinum D107,Condominium,Entire home/apt,Real Bed,3,365,strict_14_with_grace_period,6,2,3,13,2,227,0,1,https://a0.muscache.com/im/pictures/7d08e433-5...,97,289,51013381,https://www.airbnb.com/users/show/51013381,Coconut Condos,"Lahaina, Hawaii, United States",within an hour,https://a0.muscache.com/im/pictures/fa071e13-8...,https://a0.muscache.com/im/pictures/fa071e13-8...,Not Specified,99.0,No,Yes,Yes,58,58,"['email', 'phone', 'reviews', 'kba', 'work_ema...","Lahaina, HI, United States",Maui,Lahaina,Maui,United States,US,Point,-156.676460,20.875610,No,8,20,26,243,"['Air conditioning', 'Cable TV', 'Dryer', 'Ess..."
5554,9993190,https://www.airbnb.com/rooms/9993190,Just Steps from the Ocean at Premier Platinum ...,Townhouse,Entire home/apt,Real Bed,3,365,strict_14_with_grace_period,6,2,4,15,2,220,0,1,https://a0.muscache.com/im/pictures/be1978c5-6...,92,315,51013381,https://www.airbnb.com/users/show/51013381,Coconut Condos,"Lahaina, Hawaii, United States",within an hour,https://a0.muscache.com/im/pictures/fa071e13-8...,https://a0.muscache.com/im/pictures/fa071e13-8...,Not Specified,99.0,No,Yes,Yes,58,58,"['email', 'phone', 'reviews', 'kba', 'work_ema...","Lahaina, HI, United States",Lahaina,Lahaina,Maui,United States,US,Point,-156.667520,20.858940,No,0,8,31,258,"['Air conditioning', 'Dryer', 'Essentials', 'F..."